steps:
  # 1. Cache Maven dependencies
  - name: 'maven:3.9-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: ['dependency:go-offline']
    volumes:
      - name: 'maven-repo'
        path: '/root/.m2'

  # 2. Build image using Jib and push to Artifact Registry
  - name: 'maven:3.9-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: 
      - 'compile'
      - 'com.google.cloud.tools:jib-maven-plugin:build'
      # UPDATED: Points to Artifact Registry format
      - '-Dimage=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/vehicle-sales-system'
      - '-Djib.to.tags=latest,$SHORT_SHA'
    volumes:
      - name: 'maven-repo'
        path: '/root/.m2'

  # 3. Deploy to Cloud Run from Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vehicle-sales-system'
      # UPDATED: Points to the Artifact Registry image built in Step 2
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/vehicle-sales-system'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'

# Configuration Variables
substitutions:
  _REGION: us-east1          # Must match the location where you created the repo
  _REPOSITORY: vehicles_sales_repo   # Must match the name of the Artifact Registry repo you created

options:
  logging: CLOUD_LOGGING_ONLY

images:
  # UPDATED: Ensures Cloud Build knows this is the output artifact
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/vehicle-sales-system'