steps:
  # Step 1: Build the container image using Jib and Maven
  # We override the target image location using -Djib.to.image
  - name: 'maven:3.9-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: [
      'compile', 
      'jib:build', 
      '-Djib.to.image=$_IMAGE_PATH'
    ]

# Substitutions allow us to pass variables at build time
substitutions:
  _IMAGE_PATH: 'us-east1-docker.pkg.dev/my-project/my-repo/my-image' 