steps:
  # -----------------------------------------------------------------------------
  # Step 1: Build and Push Container Image using Jib
  # -----------------------------------------------------------------------------
  # We use the Maven builder image.
  # Jib builds the application and pushes the image directly to Artifact Registry.
  # We skip unit tests (-DskipTests) to speed up the build for deployment, 
  # though you can remove that flag if you want to enforce testing.
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - 'compile'
      - 'com.google.cloud.tools:jib-maven-plugin:3.4.0:build'
      - '-Dimage=us-east1-docker.pkg.dev/np-te-os-perftool/devtest-vehicle-repo/vehicle-sales-system:$COMMIT_SHA'
      - '-DskipTests'

  # -----------------------------------------------------------------------------
  # Step 2: Deploy to Cloud Run
  # -----------------------------------------------------------------------------
  # Deploys the image pushed in Step 1 to Cloud Run.
  # We use the $COMMIT_SHA as the tag to ensure every build is unique and traceable.
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vehicle-sales-system'
      - '--image'
      - 'us-east1-docker.pkg.dev/np-te-os-perftool/devtest-vehicle-repo/vehicle-sales-system:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# -----------------------------------------------------------------------------
# Substitutions / Options
# -----------------------------------------------------------------------------
options:
  logging: CLOUD_LOGGING_ONLY